#!/usr/bin/env python3
"""Export legacy relay.sqlite rows as an idempotent D1 import script."""

from __future__ import annotations

import argparse
import pathlib
import sqlite3
import sys
from typing import Any, Iterable


def sql(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    encoded = str(value).encode("utf-8").hex()
    return f"CAST(X'{encoded}' AS TEXT)"


def rows(connection: sqlite3.Connection, table: str) -> Iterable[sqlite3.Row]:
    exists = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
    ).fetchone()
    if not exists:
        return []
    return connection.execute(f'SELECT * FROM "{table}" ORDER BY rowid')


def emit(statement: str, values: Iterable[Any]) -> None:
    print(statement.format(*[sql(value) for value in values]))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("database", type=pathlib.Path, help="path to legacy relay.sqlite")
    args = parser.parse_args()
    database = args.database.resolve()
    if not database.is_file():
        parser.error(f"database does not exist: {database}")

    connection = sqlite3.connect(f"file:{database}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row

    inbound = list(rows(connection, "inbound_email"))
    outbound = list(rows(connection, "outbound_request"))
    allowlist = list(rows(connection, "allowlist_xmtp"))
    thread_map = list(rows(connection, "thread_map"))

    pending_outbound = [
        row["xmtp_msg_id"]
        for row in outbound
        if row["status"] not in ("sent", "failed", "sending")
    ]
    if pending_outbound:
        print(
            "Refusing export with nonterminal legacy outbound requests; drain the "
            f"Railway relay first (examples: {pending_outbound[:5]!r})",
            file=sys.stderr,
        )
        return 3

    normalized_allowlist: list[str] = []
    for row in allowlist:
        value = str(row["sender_inbox_or_address"]).strip().lower()
        if len(value) != 64 or any(character not in "0123456789abcdef" for character in value):
            print(
                f"Refusing non-inbox-id legacy allowlist value: {value!r}",
                file=sys.stderr,
            )
            return 2
        normalized_allowlist.append(value)

    counts = {
        "inbound_email": len(inbound),
        "outbound_request": len(outbound),
        "allowlist_xmtp": len(allowlist),
        "thread_map": len(thread_map),
    }

    print("-- Generated by cf-worker/scripts/export_legacy_d1.py")
    print("PRAGMA foreign_keys = ON;")

    for row in inbound:
        delivered_at = row["xmtp_sent_at"]
        status = "delivered" if delivered_at else "received"
        message_id = row["message_id"] or row["mailgun_message_id"]
        updated_at = delivered_at or row["received_at"]
        emit(
            """INSERT OR IGNORE INTO inbound_email(
dedupe_key, message_id, envelope_from, envelope_to, subject, text, html,
status, received_at, updated_at, xmtp_delivered_at
) VALUES ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {});""",
            (
                row["dedupe_key"],
                message_id,
                row["from"],
                row["to"],
                row["subject"] or "",
                row["text"],
                row["html"],
                status,
                row["received_at"],
                updated_at,
                delivered_at,
            ),
        )

    for row in outbound:
        legacy_status = row["status"]
        status = "uncertain" if legacy_status == "sending" else legacy_status
        error = (
            "legacy_sending_state_was_ambiguous_at_migration"
            if legacy_status == "sending"
            else row["error"]
        )
        terminal_at = row["updated_at"] if status in ("sent", "failed", "uncertain") else None
        emit(
            """INSERT OR IGNORE INTO outbound_request(
xmtp_msg_id, from_inbox, conversation_id, to_email, cc_email, bcc_email,
subject, text, html, status, provider_message_id, error,
result_delivered_at, created_at, updated_at
) VALUES ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {});""",
            (
                row["xmtp_msg_id"],
                row["from_inbox"],
                "legacy:unknown",
                row["to_email"],
                row["cc_email"],
                row["bcc_email"],
                row["subject"],
                row["text"],
                row["html"],
                status,
                row["mailgun_id"],
                error,
                terminal_at,
                row["created_at"],
                row["updated_at"],
            ),
        )

    for value in normalized_allowlist:
        emit(
            "INSERT OR IGNORE INTO allowlist_xmtp(sender_inbox_or_address, source, created_at) "
            "VALUES ({}, 'legacy_import', CURRENT_TIMESTAMP);",
            (value,),
        )

    for row in thread_map:
        emit(
            "INSERT OR IGNORE INTO thread_map(message_id, thread_id, source, created_at) "
            "VALUES ({}, {}, 'legacy_import', CURRENT_TIMESTAMP);",
            (row["message_id"], row["thread_id"]),
        )

    connection.close()
    print(
        "Exported " + ", ".join(f"{table}={count}" for table, count in counts.items()),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
